#!/usr/bin/env bash

#####################################################################
# The purpose of this script is to provide synchronization hub which
# accepts arguments and act accordingly, allowing working tree sync,
# commit, with predefined or manually altered commit-subject, and,
# if requested via script arguments, a push to the remote server.
#
# The script accepts arguments:
#
# -b or --branch
# get branch name to synchronize (default to master)
#
# -c or --commit
# enable commit after sync
#
# -f or --patchfile
# alternative path to single-file patch
#
# -g or --push
# enable pushing to the remote server after sync and commit
#
# -h or --help
# display help and usage info and exit
#
# -p or --patchdir
# alternative path to multi-file patches
#
# Author: Igor Gunia <vmta@yahoo.com>
# Date:   2019-04-05
# Ver.:   0.3
#
# v.0.3   2019-04-05
#         Include long form of options
#
# v.0.2   2019-02-14
#         Minor cleanup
#
# v.0.1   2018-09-24
#         Initial version
#####################################################################


#####################################################################
# VARIABLES
#####################################################################
#
DIR="$( cd $( dirname ${BASH_SOURCE[0]} ) > /dev/null 2>&1 && pwd )";
#
source $DIR/common/config;
#
PATCH_DIR="$DIR/git.diffs";
PATCH_FILE="$DIR/git.diff";
VERSION="0.3";
#####################################################################


#####################################################################
# REDEFINE BUILTIN COMMANDS (SILENCER), PROVIDE COMMON FUNCTIONS
#####################################################################
source common/silencer;
source common/repository;
#####################################################################


#####################################################################
# Function displayHelp
#
# In case the script is called with no arguments, or arguments are
# omitted, display short message with info on script version,
# acceptable arguments and an example.
#
displayHelp()
{

    local STRING="Script $( basename $0 ) version $VERSION\n
                 Usage:\n
                   $( basename $0 ) [b:cf:ghp:]\n\n
                 Options:\n\n
                   -b or --branch\n
                      \t Requires branch name. Defaults to \"master\".\n\n
                   -c or --commit\n
                      \t Commit changes after synchronization.\n\n
                   -f or --patchfile\n
                      \t Requires argument to set alternative path to single-file patch\n
                      \t (default: $PATCH_FILE).\n\n
                   -g or --push\n
                      \t Push the committed changes to the remote server.\n\n
                   -h or --help\n
                      \t Display this help and exit.\n\n
                   -p or --patchdir\n
                      \t Requires argument to set alternative path to patches\n
                      \t (default: $PATCH_DIR).\n\n";

    echo -e $STRING | more;

    exit 0;
}


#####################################################################
# Function doSync
#
doSync()
{
    pushd $CLONE;
    git checkout $BRANCH;
    popd;

    if [[ -d "$PATCH_DIR" && ! -z "$( ls -A $PATCH_DIR )" ]]; then
        for file in $( ls -A "$PATCH_DIR" ); do
            patch -p1 < "$PATCH_DIR/$file" && \
                rm "$PATCH_DIR/$file";
        done
        rmdir $PATCH_DIR;
    elif [[ -f "$PATCH_FILE" ]]; then
        patch -p1 < "$PATCH_FILE" && \
            rm $PATCH_FILE;
    fi

    ((FLAG_SYNC++));
}


#####################################################################
# Function doCommit
#
doCommit()
{
    pushd $MAINSTREAM;
    git checkout $BRANCH;
    local STR1="Sync to mainstream commit $( git log --format='%H (%aD)' -n 1 )";
    local STR2="$( git log --format='%s' -n 1 )";
    popd;

    pushd $CLONE;
    git checkout $BRANCH;
    git add -A;
    git commit -s -m "$STR1" -m "$STR2";
    git commit --amend --no-edit -S;
    popd;

    ((FLAG_COMMIT++));
}
#####################################################################


#####################################################################
# Function doPush
#
doPush()
{
    pushd $CLONE;
    git checkout $BRANCH;
    git push origin $BRANCH;
    popd;

    ((FLAG_PUSH++));
}
#####################################################################


#####################################################################
# Function doClean
#
#doClean()
#{
#    [[ -d $PATCH_DIR ]] && rmdir $PATCH_DIR;
#    [[ -f $PATCH_FILE ]] && rm $PATCH_FILE;
#}
#####################################################################


#####################################################################
# Check if script is called with arguments.
# Cycle through them.
if [ $# -gt 0 ]; then

    OPTIONS=$( getopt \
               --options b:,c,f:,g,h,p: \
               --longoptions branch: \
               --longoptions commit \
               --longoptions patchfile: \
               --longoptions push \
               --longoptions help \
               --longoptions patchdir: \
               --name "$( basename "$0" )" \
               -- "$@" );

    eval set -- $OPTIONS;

    while true
    do
        case "$1" in

            -b|--branch)
              # Set branch name
              [[ ! -z "$2" ]] && \
                  BRANCH=$2;
              shift;
              ;;

            -c|--commit)
              # Enable commit after sync
              FLAG_COMMIT=1;
              ;;

            -f|--patchfile)
              # Alternative path to patch-file
              [[ -f $2 ]] && \
                  PATCH_FILE=$2;
              ;;

            -g|--push)
              # Enable push after sync and commit
              FLAG_PUSH=1;
              ;;

            -h|--help)
              # Display help and usage info and exit
              displayHelp;
              ;;

            -p|--patchdir)
              # Alternative path to patches
              [[ -d $2 ]] && \
                  PATCH_DIR=$2;
              shift;
              ;;

            --)
              shift;
              break;
              ;;

        esac

        shift;

    done

    # PERFORM SOME ACTION

    #####
    # Check if PATCH_DIR has patches or PATCH_FILE exists
    # and sync, or just exit.
    #
    if [[ -d $PATCH_DIR && ! -z "$( ls -A $PATCH_DIR )" || -f $PATCH_FILE ]]; then
        doSync;
    elif [[ $FLAG_PUSH -eq 1 && $( isPushable ) -gt 0 ]]; then
        # Check if FLAG_PUSH is set and local branch tree
        # is ahead of the remote origin.
        doPush;
    else
        exit 1;
    fi

    #####
    # Check if we shall commit and act appropriately.
    #
    [[ $FLAG_COMMIT -eq 1 && $FLAG_SYNC -eq 1 ]] && doCommit;

    #####
    # Check if we shall push the commit and act accordingly.
    #
    [[ $FLAG_PUSH -eq 1 && $FLAG_COMMIT -eq 2 ]] && doPush;

else
    displayHelp;
fi

exit $?
