#!/usr/bin/env bash


# Stage 1 - get diff file

DIFFFILE="$( pwd )/git.diffs";
DIFFTMP="$( pwd )/diff.tmp";
FILES=();
SUBST="$( pwd )/common/subst";

pushd umkoin;
git pull origin master;
for SHA1 in $( git log --format='%s' | grep "Sync to mainstream commit" | awk '{ print $5 }' ); do
    break;
done
popd;


pushd bitcoin;
git pull origin master;
# -=or=-
# git fetch;
# git merge;

git diff $SHA1 HEAD | sed -f $SUBST > $DIFFFILE; # auto apply substitions

## set stage 1.1 = get per-file-diffs with auto substitution
for FILE in $( git diff --name-only $SHA1 HEAD ); do
    FILES+=( $FILE );

    [ ! -d $DIFFTMP ] && mkdir $DIFFTMP;
    DEST="$DIFFTMP/$( echo ${FILE##*/} )";
#
    git diff "../umkoin/$FILE" $FILE | sed -f $SUBST > $DEST;
#    git diff "../umkoin/$FILE" $FILE > $DEST;

done;
popd;


printf "Diff file:\t%s\n" $DIFFFILE;
printf "Files to patch:\t%d\n" ${#FILES[@]};
printf "              :\t%s\n" ${FILES[@]};



exit $?
